# Generated by Django 4.1.7 on 2023-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='скидка'),
        ),
    ]
