# Generated by Django 4.1.7 on 2023-03-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
