# Generated by Django 4.1.7 on 2023-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='имя')),
                ('job_title', models.CharField(max_length=64, verbose_name='должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': ('команда',),
                'verbose_name_plural': 'команда',
            },
        ),
    ]
