# Generated by Django 4.1.7 on 2023-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='descr',
            field=models.CharField(default='пусто', max_length=4096, verbose_name='описание'),
        ),
    ]
