# Generated by Django 4.1.7 on 2023-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_team_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=32, verbose_name='сильные cтороны')),
                ('descr', models.CharField(default='есть причины', max_length=4096, verbose_name='описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
