# Generated by Django 4.1.7 on 2023-03-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': ('преимущество',), 'verbose_name_plural': 'преимущества'},
        ),
    ]
