# Generated by Django 4.1.7 on 2023-03-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_aboutus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='characteristic',
            new_name='char',
        ),
    ]
