# Generated by Django 4.1.7 on 2023-04-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_characteristic_aboutus_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='блог')),
                ('body', models.CharField(max_length=3072, verbose_name='текст поста')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
