# Generated by Django 4.1.7 on 2023-04-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': ('блог',), 'verbose_name_plural': 'блоги'},
        ),
    ]
