# Generated by Django 4.1.7 on 2023-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='акция')),
                ('image', models.ImageField(upload_to='promotion/', verbose_name='банер акции')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': ('акция',),
                'verbose_name_plural': 'акции',
            },
        ),
    ]
