# Generated by Django 4.1.7 on 2023-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='низвание')),
                ('image', models.ImageField(upload_to='insta/', verbose_name='фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': ('интсанрам',),
                'verbose_name_plural': 'инстаграм',
            },
        ),
    ]
