# Generated by Django 4.1.7 on 2023-04-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='название')),
                ('image', models.ImageField(upload_to='Gallery/', verbose_name='фото')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': ('галерея',),
                'verbose_name_plural': 'галереи',
            },
        ),
    ]
